import type { RssFeedConfig } from "../shared/rss.js";
import { DOMESTIC_AI_KEYWORD_FILTERS } from "./domesticSources.js";

export const rssFeeds: RssFeedConfig[] = [
  {
    id: "anthropic-newsroom",
    name: "Anthropic Newsroom",
    source: "Anthropic",
    url: "https://www.anthropic.com/news",
    format: "anthropic-newsroom",
    layer: "official",
    kind: "news",
    category: "Model",
    region: "US",
  },
  {
    id: "google-ai-blog",
    name: "Google AI Blog",
    source: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    layer: "official",
    kind: "news",
    category: "Model",
    region: "US",
  },
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    source: "TechCrunch",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    layer: "general-news",
    kind: "news",
    category: "Product",
    region: "US",
  },
  {
    id: "wired-ai",
    name: "WIRED Artificial Intelligence",
    source: "WIRED",
    url: "https://www.wired.com/feed/tag/ai/latest/rss",
    layer: "general-news",
    kind: "news",
    category: "Product",
    region: "US",
  },
  {
    id: "mit-technology-review-ai",
    name: "MIT Technology Review AI",
    source: "MIT Technology Review",
    url: "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
    layer: "general-news",
    kind: "news",
    category: "Policy",
    region: "US",
  },
  {
    id: "the-verge-ai",
    name: "The Verge AI",
    source: "The Verge",
    url: "https://www.theverge.com/rss/ai/index.xml",
    layer: "general-news",
    kind: "news",
    category: "Product",
    region: "US",
  },
  {
    id: "openai-news",
    name: "OpenAI News",
    source: "OpenAI",
    url: "https://openai.com/news/rss.xml",
    layer: "official",
    kind: "news",
    category: "Model",
    region: "US",
  },
  {
    id: "mistral-newsroom",
    name: "Mistral AI News",
    source: "Mistral",
    url: "https://mistral.ai/news",
    format: "mistral-newsroom",
    layer: "official",
    kind: "news",
    category: "Model",
    region: "Europe",
  },
  {
    id: "cohere-changelog",
    name: "Cohere Release Notes",
    source: "Cohere",
    url: "https://docs.cohere.com/changelog",
    format: "cohere-changelog",
    layer: "official",
    kind: "news",
    category: "Model",
    region: "US",
  },
  {
    id: "microsoft-official-blog",
    name: "Microsoft Official Blog",
    source: "Microsoft",
    url: "https://blogs.microsoft.com/feed/",
    layer: "official",
    kind: "news",
    category: "Infrastructure",
    region: "US",
  },
  {
    id: "nvidia-blog",
    name: "NVIDIA Blog",
    source: "NVIDIA",
    url: "https://blogs.nvidia.com/feed/",
    layer: "official",
    kind: "news",
    category: "Infrastructure",
    region: "US",
  },
  {
    id: "meta-product-news",
    name: "Meta Product News",
    source: "Meta",
    url: "https://about.fb.com/news/category/product-news/feed/",
    layer: "official",
    kind: "news",
    category: "Product",
    region: "US",
  },
  {
    id: "aws-machine-learning-blog",
    name: "AWS Machine Learning Blog",
    source: "AWS",
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    layer: "official",
    kind: "news",
    category: "Infrastructure",
    region: "US",
  },
  {
    id: "hugging-face-blog",
    name: "Hugging Face Blog",
    source: "Hugging Face",
    url: "https://huggingface.co/blog/feed.xml",
    layer: "specialist-news",
    kind: "news",
    category: "Model",
    region: "Europe",
  },
  {
    id: "ai-news",
    name: "AI News",
    source: "AI News",
    url: "https://www.artificialintelligence-news.com/feed/",
    layer: "specialist-news",
    kind: "news",
    category: "Product",
    region: "Europe",
  },
  {
    id: "etnews-ai",
    name: "전자신문 AI",
    source: "전자신문",
    url: "http://rss.etnews.com/04046.xml",
    layer: "general-news",
    kind: "news",
    category: "Product",
    region: "Asia",
  },
  {
    id: "zdnet-korea",
    name: "ZDNet Korea",
    source: "ZDNet Korea",
    url: "https://feeds.feedburner.com/zdkorea",
    layer: "general-news",
    kind: "news",
    category: "Product",
    region: "Asia",
    keywordFilters: DOMESTIC_AI_KEYWORD_FILTERS,
  },
  {
    id: "ai-times",
    name: "AI타임스",
    source: "AI타임스",
    url: "https://cdn.aitimes.com/rss/gn_rss_allArticle.xml",
    layer: "specialist-news",
    kind: "news",
    category: "Product",
    region: "Asia",
  },
  {
    id: "skt-newsroom",
    name: "SKT 뉴스룸",
    source: "SKT 뉴스룸",
    url: "https://news.sktelecom.com/feed",
    layer: "official",
    kind: "news",
    category: "Product",
    region: "Asia",
    keywordFilters: DOMESTIC_AI_KEYWORD_FILTERS,
  },
  {
    id: "samsung-sds-news",
    name: "삼성SDS 언론보도",
    source: "삼성SDS",
    url: "https://www.samsungsds.com/kr/news/media_report_ko_rss.xml",
    linkBaseUrl: "https://www.samsungsds.com",
    layer: "official",
    kind: "news",
    category: "Product",
    region: "Asia",
    keywordFilters: DOMESTIC_AI_KEYWORD_FILTERS,
  },
  {
    id: "naver-d2",
    name: "NAVER D2",
    source: "NAVER D2",
    url: "https://d2.naver.com/d2.atom",
    layer: "specialist-news",
    kind: "news",
    category: "Model",
    region: "Asia",
    keywordFilters: DOMESTIC_AI_KEYWORD_FILTERS,
  },
  {
    id: "lg-ai-research-news",
    name: "LG AI Research News",
    source: "LG AI Research",
    url: "https://www.lgresearch.ai/api/board/blog/list?pg=1&pgSz=12&schExpsYn=Y&schLangTp=KR&sordFld=sort&sordMetd=ASC&schNotCatgCd=BAAACC",
    format: "lg-ai-research-api",
    layer: "official",
    kind: "news",
    category: "Model",
    region: "Asia",
  },
  {
    id: "arxiv-cs-ai",
    name: "arXiv cs.AI",
    source: "arXiv",
    url: "https://export.arxiv.org/rss/cs.AI",
    layer: "research",
    kind: "research",
    category: "Research",
    region: "Global",
  },
  {
    id: "arxiv-cs-lg",
    name: "arXiv cs.LG",
    source: "arXiv",
    url: "https://export.arxiv.org/rss/cs.LG",
    layer: "research",
    kind: "research",
    category: "Research",
    region: "Global",
  },
  {
    id: "arxiv-cs-cl",
    name: "arXiv cs.CL",
    source: "arXiv",
    url: "https://export.arxiv.org/rss/cs.CL",
    layer: "research",
    kind: "research",
    category: "Research",
    region: "Global",
  },
];
