import type { RssFeedConfig } from "../shared/rss.js";

export const rssFeeds: RssFeedConfig[] = [
  {
    id: "anthropic-newsroom",
    name: "Anthropic Newsroom",
    source: "Anthropic",
    url: "https://www.anthropic.com/news",
    format: "anthropic-newsroom",
    kind: "news",
    category: "Model",
    region: "US",
  },
  {
    id: "google-ai-blog",
    name: "Google AI Blog",
    source: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    kind: "news",
    category: "Model",
    region: "US",
  },
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    source: "TechCrunch",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    kind: "news",
    category: "Product",
    region: "US",
  },
  {
    id: "openai-news",
    name: "OpenAI News",
    source: "OpenAI",
    url: "https://openai.com/news/rss.xml",
    kind: "news",
    category: "Model",
    region: "US",
  },
  {
    id: "microsoft-official-blog",
    name: "Microsoft Official Blog",
    source: "Microsoft",
    url: "https://blogs.microsoft.com/feed/",
    kind: "news",
    category: "Infrastructure",
    region: "US",
  },
  {
    id: "nvidia-blog",
    name: "NVIDIA Blog",
    source: "NVIDIA",
    url: "https://blogs.nvidia.com/feed/",
    kind: "news",
    category: "Infrastructure",
    region: "US",
  },
  {
    id: "meta-product-news",
    name: "Meta Product News",
    source: "Meta",
    url: "https://about.fb.com/news/category/product-news/feed/",
    kind: "news",
    category: "Product",
    region: "US",
  },
  {
    id: "aws-machine-learning-blog",
    name: "AWS Machine Learning Blog",
    source: "AWS",
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    kind: "news",
    category: "Infrastructure",
    region: "US",
  },
  {
    id: "hugging-face-blog",
    name: "Hugging Face Blog",
    source: "Hugging Face",
    url: "https://huggingface.co/blog/feed.xml",
    kind: "news",
    category: "Model",
    region: "Europe",
  },
  {
    id: "arxiv-cs-ai",
    name: "arXiv cs.AI",
    source: "arXiv",
    url: "https://export.arxiv.org/rss/cs.AI",
    kind: "research",
    category: "Research",
    region: "Global",
  },
  {
    id: "arxiv-cs-lg",
    name: "arXiv cs.LG",
    source: "arXiv",
    url: "https://export.arxiv.org/rss/cs.LG",
    kind: "research",
    category: "Research",
    region: "Global",
  },
  {
    id: "arxiv-cs-cl",
    name: "arXiv cs.CL",
    source: "arXiv",
    url: "https://export.arxiv.org/rss/cs.CL",
    kind: "research",
    category: "Research",
    region: "Global",
  },
];
